version: '2'
services:
  postgres:
    image: postgres
    ports:
     - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: block-test
